server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: vehicle-service-route
        uri: lb://vehicle-service  # Use service discovery to route to 'vehicle-service'
        predicates:
        - Path=/vehicle-service/** # Match requests starting with /vehicle-service
        filters:
        - RewritePath=RewritePath=/vehicle-service/(?<suburl>.*),/vehicle-path/${suburl} # Just a direct rewrite
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
